"""Report generation for DTaaS-Bench results."""

import json
from datetime import datetime

from .scorer import WEIGHTS, DIMENSION_LABELS, composite_score, rating_tier


def generate_markdown(results: dict, runtime_name: str = "Unknown") -> str:
    """Generate a Markdown report from benchmark results."""
    dim_scores = results.get("dimension_scores", {})
    total = composite_score(dim_scores)
    tier = rating_tier(total)

    lines = [
        f"# DTaaS-Bench Results: {runtime_name}",
        "",
        f"**Date**: {results.get('date', datetime.now().isoformat()[:10])}",
        f"**Benchmark Version**: DTaaS-Bench v0.1",
        f"**Runtime URL**: {results.get('url', 'N/A')}",
        "",
        "---",
        "",
        f"## Composite Score: {total}/100 — {tier}",
        "",
        "### Dimension Breakdown",
        "",
        "| Dimension | Weight | Score | Weighted |",
        "|-----------|--------|-------|----------|",
    ]

    for dim, weight in WEIGHTS.items():
        score = dim_scores.get(dim, 0)
        weighted = round(score * weight, 2)
        label = DIMENSION_LABELS.get(dim, dim)
        lines.append(f"| {label} | {weight:.2f} | {score:.0f} | {weighted:.2f} |")

    lines.append(f"| **Total** | **1.00** | | **{total:.1f}** |")
    lines.append("")

    # Details per dimension
    details = results.get("dimension_details", {})
    if details:
        lines.append("---")
        lines.append("")
        lines.append("## Dimension Details")
        lines.append("")
        for dim, detail in details.items():
            label = DIMENSION_LABELS.get(dim, dim)
            lines.append(f"### {label}")
            lines.append("")
            if isinstance(detail, dict):
                for k, v in detail.items():
                    if k == "score":
                        continue
                    lines.append(f"- **{k}**: {v}")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"*Generated by DTaaS-Bench v0.1 — {datetime.now().isoformat()[:10]}*")
    return "\n".join(lines)


def generate_html(results: dict, runtime_name: str = "Unknown") -> str:
    """Generate a self-contained HTML report from benchmark results."""
    dim_scores = results.get("dimension_scores", {})
    total = composite_score(dim_scores)
    tier = rating_tier(total)
    date = results.get("date", datetime.now().isoformat()[:10])

    tier_color = {
        "Category Leader": "#22c55e",
        "Production-Grade": "#3b82f6",
        "Competitive": "#8b5cf6",
        "Emerging": "#f59e0b",
        "Specialized": "#f97316",
        "Early Stage": "#ef4444",
    }.get(tier, "#6b7280")

    rows = []
    for dim, weight in WEIGHTS.items():
        score = dim_scores.get(dim, 0)
        weighted = round(score * weight, 2)
        label = DIMENSION_LABELS.get(dim, dim)
        bar_width = max(2, int(score))
        bar_color = (
            "#22c55e" if score >= 80 else "#f59e0b" if score >= 60 else "#ef4444"
        )
        rows.append(f"""
        <tr>
            <td>{label}</td>
            <td>{weight:.2f}</td>
            <td>
                <div style="display:flex;align-items:center;gap:8px">
                    <div style="background:{bar_color};height:18px;width:{bar_width}%;border-radius:3px;min-width:4px"></div>
                    <span>{score:.0f}</span>
                </div>
            </td>
            <td>{weighted:.2f}</td>
        </tr>""")

    detail_sections = []
    details = results.get("dimension_details", {})
    for dim, detail in details.items():
        label = DIMENSION_LABELS.get(dim, dim)
        items = ""
        if isinstance(detail, dict):
            for k, v in detail.items():
                if k == "score":
                    continue
                items += f"<li><strong>{k}</strong>: {_escape(str(v))}</li>\n"
        detail_sections.append(f"<h3>{label}</h3><ul>{items}</ul>")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>DTaaS-Bench Results — {_escape(runtime_name)}</title>
<style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #f8fafc; color: #1e293b; padding: 2rem; max-width: 900px; margin: 0 auto; }}
    h1 {{ font-size: 1.8rem; margin-bottom: 0.5rem; }}
    h2 {{ font-size: 1.3rem; margin: 1.5rem 0 0.8rem; color: #334155; }}
    h3 {{ font-size: 1.1rem; margin: 1rem 0 0.5rem; color: #475569; }}
    .meta {{ color: #64748b; font-size: 0.9rem; margin-bottom: 1.5rem; }}
    .score-card {{ background: white; border-radius: 12px; padding: 2rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin-bottom: 1.5rem; text-align: center; }}
    .score-number {{ font-size: 4rem; font-weight: 800; color: #0f172a; }}
    .score-tier {{ display: inline-block; padding: 0.3rem 1rem; border-radius: 20px; color: white; font-weight: 600; font-size: 1.1rem; margin-top: 0.5rem; }}
    table {{ width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin-bottom: 1.5rem; }}
    th {{ background: #f1f5f9; text-align: left; padding: 0.75rem 1rem; font-weight: 600; font-size: 0.85rem; color: #475569; text-transform: uppercase; letter-spacing: 0.05em; }}
    td {{ padding: 0.75rem 1rem; border-top: 1px solid #e2e8f0; }}
    tr:hover {{ background: #f8fafc; }}
    .details {{ background: white; border-radius: 8px; padding: 1.5rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin-bottom: 1rem; }}
    .details ul {{ padding-left: 1.5rem; }}
    .details li {{ margin: 0.3rem 0; font-size: 0.9rem; }}
    .footer {{ text-align: center; color: #94a3b8; font-size: 0.8rem; margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e2e8f0; }}
    .nn {{ font-weight: 600; color: #64748b; }}
</style>
</head>
<body>
<h1>DTaaS-Bench Results</h1>
<div class="meta">{_escape(runtime_name)} — {date} — DTaaS-Bench v0.1</div>

<div class="score-card">
    <div class="score-number">{total:.0f}</div>
    <div>/100</div>
    <div class="score-tier" style="background:{tier_color}">{tier}</div>
</div>

<h2>Dimension Breakdown</h2>
<table>
    <thead>
        <tr><th>Dimension</th><th>Weight</th><th>Score</th><th>Weighted</th></tr>
    </thead>
    <tbody>
        {"".join(rows)}
        <tr style="font-weight:700;border-top:2px solid #cbd5e1">
            <td>Composite</td><td>1.00</td><td></td><td>{total:.1f}</td>
        </tr>
    </tbody>
</table>

{"<h2>Dimension Details</h2>" if detail_sections else ""}
{"".join(f'<div class="details">{s}</div>' for s in detail_sections)}

<div class="footer">
    <span class="nn">DTaaS-Bench v0.1</span> — Published by Nova Nuggets — novanuggets.com
</div>
</body>
</html>"""


def _escape(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
